"""empty message

Revision ID: 3431efa062d9
Revises: fdf3226632d4
Create Date: 2024-11-04 03:18:53.004015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3431efa062d9'
down_revision: Union[str, None] = 'fdf3226632d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала создаем новый тип данных в базе данных
    op.execute(
        "CREATE TYPE characteristictype AS ENUM ('relationship', 'yourself', 'attract', 'worldview');"
    )
    op.add_column('Characteristics', sa.Column('type_characteristic', sa.Enum('relationship', 'yourself', 'attract', 'worldview', name='characteristictype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Characteristics', 'type_characteristic')
    # Удаляем созданный тип данных
    op.execute("DROP TYPE characteristictype;")
    # ### end Alembic commands ###

