"""empty message

Revision ID: a0f83e17747b
Revises: 628ce6f89273
Create Date: 2024-10-30 04:52:47.642872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0f83e17747b'
down_revision: Union[str, None] = '628ce6f89273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'gender',
               existing_type=postgresql.ENUM('male', 'female', name='gender'),
               nullable=True)
    op.alter_column('User', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('User', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('User', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('User', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('User', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('User', 'gender',
               existing_type=postgresql.ENUM('male', 'female', name='gender'),
               nullable=False)
    # ### end Alembic commands ###
