"""empty message

Revision ID: fdf3226632d4
Revises: a0f83e17747b
Create Date: 2024-11-03 00:38:11.033556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdf3226632d4'
down_revision: Union[str, None] = 'a0f83e17747b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AnswUserChar', sa.Column('importance', sa.Enum('necessarily_yes', 'important_yes', 'more_yes', 'neutral', 'more_no', 'necessarily_no', name='importance'), nullable=False))
    op.add_column('Answer', sa.Column('characteristic_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Answer', 'Characteristics', ['characteristic_id'], ['id'], ondelete='CASCADE')
    op.drop_column('Answer', 'importance')
    op.add_column('User', sa.Column('preview', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'preview')
    op.add_column('Answer', sa.Column('importance', postgresql.ENUM('necessarily_yes', 'important_yes', 'more_yes', 'neutral', 'more_no', 'necessarily_no', name='importance'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Answer', type_='foreignkey')
    op.drop_column('Answer', 'characteristic_id')
    op.drop_column('AnswUserChar', 'importance')
    # ### end Alembic commands ###
